version: "3"
services:
  pg:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: XML
      POSTGRES_PASSWORD: ftn
      POSTGRES_DB: XML_TEST
    ports:
      - 4002:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U XML -d \"XML_TEST\"" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  user-service:
    hostname: user-service
    build: .
    restart: always
    environment:
      - DB_USER=XML
      - DB_HOST=pg
      - DB_PASSWORD=ftn
      - DB_NAME=XML_TEST
      - DB_PORT=5432
      - USER_SERVICE_HOST=user-service
    ports:
      - "8081:8081"
    networks:
      - backend
    depends_on:
      pg:
        condition: service_healthy

networks:
  backend:
    driver: bridge


